---
- name: Create apache shibboleth config
  template:
    src: shib.conf.j2
    dest: "{{ apache_conf_path }}/shib.conf"
  notify: __apache_restart
  when: "{{ shibboleth_activate_apache }}" == true

- name: Generate shibboleth-certs
  command: 
    argv:
      - /usr/bin/bash 
      - /etc/shibboleth/keygen.sh 
      - -o 
      - "{{ mounted_nfs_share }}"
    creates: "{{ mounted_nfs_share }}/sp-cert.pem"

- name: Copy sp-cert.pem to /etc/shibboleth
  copy:
    src: "{{ mounted_nfs_share }}/sp-cert.pem"
    dest: /etc/shibboleth/sp-cert.pem
    remote_src: yes

- name: Copy sp-key.pem to /etc/shibboleth 
  copy:
    src: "{{ mounted_nfs_share }}/sp-key.pem"
    dest: /etc/shibboleth/sp-key.pem
    remote_src: yes

- name: Get ADFS Metadata
  command:
    command_warnings: false
    argv: 
      - /usr/bin/curl
      - "https://{{ shibboleth_adfs_server_name }}/FederationMetadata/2007-06/FederationMetadata.xml"
  register: get_adfs_metadata

- name: Create shibboleth2.xml
  template:
    src: shibboleth2.xml.j2
    dest: "/etc/shibboleth/shibboleth2.xml"
  notify: 
    - __shibd_restart
    - __apache_restart

- name: Create attribute-map.xml
  template:
    src: attribute-map.xml.j2
    dest: "/etc/shibboleth/attribute-map.xml"
  notify: 
    - __shibd_restart
    - __apache_restart

- name: Create ADFS Metadata
  command:
    argv:
      - /usr/bin/php
      - "{{ owncloud_deploy_path }}/apps/user_shibboleth/tools/adfs2fed.php"
      - "https://{{ shibboleth_adfs_server_name }}/FederationMetadata/2007-06/FederationMetadata.xml"
      - "{{ shibboleth_ad_domain }}"
  register: create_adfs_metadata

- name: Write ADFS Metadata to File
  copy:
    dest: /etc/shibboleth/owncloud-metadata.xml
    content: "{{ create_adfs_metadata.stdout }}"
    owner: root
    group: root
    mode: '0644'

