---
- name: Create apache shibboleth config
  template:
    src: shib.conf.j2
    dest: "{{ apache_conf_path }}/shib.conf"
  notify: __apache_restart

- name: Generate shibboleth-certs
  command: 
    argv:
      - /usr/bin/bash 
      - /etc/shibboleth/keygen.sh 
      - -o 
      - "{{ mounted_nfs_share }}"
    creates: "{{ mounted_nfs_share }}"/sp-cert.pem

- name: Copy sp-cert.pem to /etc/shibboleth
  copy:
    src: "{{ mounted_nfs_share }}"/sp-cert.pem
    dest: /etc/shibboleth/sp-cert.pem
    remote_src: yes

- name: Copy sp-key.pem to /etc/shibboleth 
  copy:
    src: "{{ mounted_nfs_share }}"/sp-key.pem
    dest: /etc/shibboleth/sp-key.pem
    remote_src: yes


